# Generated by Django 4.0.1 on 2022-01-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.IntegerField()),
                ('section', models.CharField(max_length=25)),
                ('photo', models.FileField(upload_to='photos')),
            ],
        ),
    ]
